<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace MultiAuthTester\MultipleAuthTester\Models\Operations;


class GetCarsByNameResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * error payload
     * 
     * @var ?\MultiAuthTester\MultipleAuthTester\Models\Shared\ErrorModel $errorModel
     */
	
    public ?\MultiAuthTester\MultipleAuthTester\Models\Shared\ErrorModel $errorModel = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * car response
     * 
     * @var ?array<\MultiAuthTester\MultipleAuthTester\Models\Shared\Car> $classes
     */
	
    public ?array $classes = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorModel = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->classes = null;
	}
}
