<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace MultiAuthTester\MultipleAuthTester\Models\Operations;

use \MultiAuthTester\MultipleAuthTester\Utils\SpeakeasyMetadata;
class GetCarsByIdSecurity
{
	#[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=query,name=api_key')]
    public ?string $apiKey = null;
    
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=basic')]
    public ?\MultiAuthTester\MultipleAuthTester\Models\Shared\SchemeHTTPBasic $httpBasic = null;
    
	public function __construct()
	{
		$this->apiKey = null;
		$this->httpBasic = null;
	}
}
