<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace MultiAuthTester\MultipleAuthTester\Models\Operations;


class GetCarsByNameResponse
{
    /**
     * car response
     * 
     * @var ?array<\MultiAuthTester\MultipleAuthTester\Models\Shared\Car> $cars
     */
	
    public ?array $cars = null;
    
	
    public string $contentType;
    
    /**
     * error payload
     * 
     * @var ?\MultiAuthTester\MultipleAuthTester\Models\Shared\ErrorModel $errorModel
     */
	
    public ?\MultiAuthTester\MultipleAuthTester\Models\Shared\ErrorModel $errorModel = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->cars = null;
		$this->contentType = "";
		$this->errorModel = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
