<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace MultiAuthTester\MultipleAuthTester;

/**
 * MultipleAuthTester - Code Generators Comparison App Multiple Auths: This is a sample spec to compare SDKs generated by different code generators.
 * 
 * @package MultiAuthTester\MultipleAuthTester
 * @access public
 */
class MultipleAuthTester
{
	public const SERVERS = [
        /** Development server */
		'https://development.gigantic-server.com/v1',
        /** Staging server */
		'https://staging.gigantic-server.com/v1',
        /** Production server */
		'https://api.gigantic-server.com/v1',
	];
  	
    /**
     * Car operations
     * 
     * @var Cars $$cars
     */
	public Cars $cars;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return MultipleAuthTesterBuilder
	 */
	public static function builder(): MultipleAuthTesterBuilder
	{
		return new MultipleAuthTesterBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->cars = new Cars($this->sdkConfiguration);
	}
}